name: Test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          FORCE_COLOR: true
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: image_snapshots_diff_output
          path: test/__image_snapshots__/__diff_output__/